### ISSUE TITLE
Users should see their house represented visually given a valid house-layout file.

### ISSUE THREAD

**Issue by gregtuc** [gregtuc/SmartHomeSimulator#1]
As a user I want to be able to:
1) Select an option to upload a house-layout file.
2) Select the house-layout file from my computer.
3) Upload the house-layout file to the simulator.
4) See my house represented visually in the simulator.

**Comment by AdrienKamran** [comment]
The current implementation of this feature involves the use of a Room class (to hold Room objects and their attributes) and a 2D 4x4 matrix made of Arraylists.

![Screenshot 2020-10-16 224656](https://user-images.githubusercontent.com/50927558/96328105-7c3e2980-100d-11eb-937c-46944d2277be.png)

The text file "layout.txt" is read by a class "LayoutParser" which, as the name implies, parses the layout file in two steps.

**STEP 1:** the grid is split row-by-row and Room objects are created+assigned wherever the user has left a number.
The attributes "graphNumber", "gridCol" and "gridRow" are saved to the room in this step.
**STEP 2:** each room is given its remaining attributes: "roomName", "door" and "window". The latter two attributes are Booleans, where "true" means "there is one" and "false" means "there are none". 

Here is a sample "layout.txt" file:
![Screenshot 2020-10-17 000117](https://user-images.githubusercontent.com/50927558/96328221-80b71200-100e-11eb-9cce-8a68069fb1c9.png)

Here is a readout from the console, verifying the parsed data. [0] represents the absence of a room.
![Screenshot 2020-10-17 000038](https://user-images.githubusercontent.com/50927558/96328233-9a585980-100e-11eb-8a2e-2f9179f01f5b.png)

Please see commits from the 13th of October to the 17th of October on the dev-layout branch for more details:
https://github.com/gregtuc/SmartHomeSimulator/commits/dev-layout
