### ISSUE TITLE
Create an Exception Class, implement it, and justify its existence.

### ISSUE THREAD

**Issue by AdrienKamran** [gregtuc/SmartHomeSimulator#42]
Self-explanatory. This will need to be shown off in the report, so please include a screenshot in the comments here before closing the issue.

**SOME IDEAS:**
-> House layout parser: the house must exist as a single unit.
-> Two profiles with the same name cannot co-exist.

**Comment by gregtuc** [comment]
Issue was closed with commit ID: b7f5d25
