### ISSUE TITLE
Refactor a section of code.

### ISSUE THREAD

**Issue by AdrienKamran** [gregtuc/SmartHomeSimulator#43]
**FULL TASK DESCRIPTION:**
You must provide evidence of refactoring that you applied for this delivery. In the documentation provide details about the commit ID, classes involved, the rationale of why you choose to refactor those classes, and evidence that you execute the corresponding Junit tests passed after the  refactoring change. If you needed to update the Junit tests for those classes, add a brief description of the changes.

**Notice that the following refactoring methods alone do not qualify for this mark:** _renaming, extract variable._

**Comment by gregtuc** [comment]
![image](https://user-images.githubusercontent.com/60011793/101288719-0b71ed00-37c6-11eb-9b1e-478d3a734881.png)
Tests passing for #43 after refactoring
